// Banco de dados dos produtos
const data = [
	{
		id: 0,
		img: "./img/pikachu.png",
		nameItem: "Pikachu",
		description: "Pokemon de tipo elétrico, com altos atributos de SPD e ATK.",
		value: 25,
		addCart: "Adicionar ao carrinho",
		tag: ["Elétrico"],
	},
	{
		id: 1,
		img: "./img/raichu.png",
		nameItem: "Raichu",
		description:
			"Esse pokemon é muito rápido e consegue causar muito dano com suas skills.",
		value: 100,
		addCart: "Adicionar ao carrinho",
		tag: ["Elétrico"],
	},
	{
		id: 2,
		img: "./img/bulbasaur.png",
		nameItem: "Bulbasaur",
		description:
			"Pokemon de tipo planta, com altos atributos de SPATK e SPDEF.",
		value: 25,
		addCart: "Adicionar ao carrinho",
		tag: ["Planta/Veneno"],
	},
	{
		id: 3,
		img: "./img/ivysaur.png",
		nameItem: "Ivysaur",
		description:
			"Uma boa escolha para tankar e também consegue dar um dano razoável com sua Razor Leaf.",
		value: 50,
		addCart: "Adicionar ao carrinho",
		tag: ["Planta/Veneno"],
	},
	{
		id: 4,
		img: "./img/venusaur.png",
		nameItem: "Venusaur",
		description:
			"Causa bastante dano e tanka com suas skills de Solar Beam e Mega Drain respectivamente.",
		value: 100,
		addCart: "Adicionar ao carrinho",
		tag: ["Planta/Veneno"],
	},
	{
		id: 5,
		img: "./img/charmander.png",
		nameItem: "Charmander",
		description:
			"Considerado o melhor pokemon inicial, esse pokemon tem um alto atributo de SPATK e ATK.",
		value: 30,
		addCart: "Adicionar ao carrinho",
		tag: ["Fogo"],
	},
	{
		id: 6,
		img: "./img/charmeleon.png",
		nameItem: "Charmeleon",
		description: "Esse pokemon tem um alto atributo de SPATK e SPD.",
		value: 70,
		addCart: "Adicionar ao carrinho",
		tag: ["Fogo"],
	},
	{
		id: 7,
		img: "./img/charizard.png",
		nameItem: "Charizard",
		description:
			"Salvo de explicações o Charizard é um pokemon muito forte e consegue acabar o combate em segundos.",
		value: 150,
		addCart: "Adicionar ao carrinho",
		tag: ["Fogo/Voador"],
	},
	{
		id: 8,
		img: "./img/squirtle.png",
		nameItem: "Squirtle",
		description: "Pokemon de tipo água, com altos atributos de SPDEF e DEF.",
		value: 25,
		addCart: "Adicionar ao carrinho",
		tag: ["Água"],
	},
	{
		id: 9,
		img: "./img/Wartortle.png",
		nameItem: "Wartortle",
		description: "Pokemon de tipo água, com altos atributos de SPDEF e DEF.",
		value: 50,
		addCart: "Adicionar ao carrinho",
		tag: ["Água"],
	},
	{
		id: 10,
		img: "./img/blastoise.png",
		nameItem: "Blastoise",
		description: "Pokemon de tipo água, com altos atributos de SPDEF e DEF.",
		value: 100,
		addCart: "Adicionar ao carrinho",
		tag: ["Água"],
	},
];
