// Banco de dados dos produtos
const data = [
	{
		id: 0,
		img: "./img/pikachu.png",
		nameItem: "Pikachu",
		description: "Pokemon de tipo elétrico, com altos atributos de SPD e ATK.",
		value: 25,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Elétrico"],
	},
	{
		id: 1,
		img: "./img/raichu.png",
		nameItem: "Raichu",
		description:
			"Esse pokemon é muito rápido e consegue causar muito dano com suas skills.",
		value: 100,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Elétrico"],
	},
	{
		id: 2,
		img: "./img/bulbasaur.png",
		nameItem: "Bulbasaur",
		description:
			"Pokemon de tipo planta, com altos atributos de SPATK e SPDEF.",
		value: 25,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Planta", "Veneno"],
	},
	{
		id: 3,
		img: "./img/ivysaur.png",
		nameItem: "Ivysaur",
		description:
			"Uma boa escolha para tankar e também consegue dar um dano razoável com sua Razor Leaf.",
		value: 50,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Planta", "Veneno"],
	},
	{
		id: 4,
		img: "./img/venusaur.png",
		nameItem: "Venusaur",
		description:
			"Causa bastante dano e tanka com suas skills de Solar Beam e Mega Drain respectivamente.",
		value: 100,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Planta", "Veneno"],
	},
	{
		id: 5,
		img: "./img/charmander.png",
		nameItem: "Charmander",
		description:
			"Considerado o melhor pokemon inicial, esse pokemon tem um alto atributo de SPATK e ATK.",
		value: 30,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Fogo"],
	},
	{
		id: 6,
		img: "./img/charmeleon.png",
		nameItem: "Charmeleon",
		description: "Esse pokemon tem um alto atributo de SPATK e SPD.",
		value: 70,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Fogo"],
	},
	{
		id: 7,
		img: "./img/charizard.png",
		nameItem: "Charizard",
		description:
			"Salvo de explicações o Charizard é um pokemon muito forte e consegue acabar o combate em segundos.",
		value: 150,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Fogo", "Voador"],
	},
	{
		id: 8,
		img: "./img/squirtle.png",
		nameItem: "Squirtle",
		description: "Pokemon de tipo água, com altos atributos de SPDEF e DEF.",
		value: 25,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Água"],
	},
	{
		id: 9,
		img: "./img/Wartortle.png",
		nameItem: "Wartortle",
		description: "Pokemon de tipo água, com altos atributos de SPDEF e DEF.",
		value: 50,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Água"],
	},
	{
		id: 10,
		img: "./img/blastoise.png",
		nameItem: "Blastoise",
		description: "Pokemon de tipo água, com altos atributos de SPDEF e DEF.",
		value: 100,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Água"],
	},
	{
		id: 11,
		img: "../img/Insignia_Rocha.webp",
		nameItem: "Insígnia Rocha",
		description:
			"Insígnia Rocha, obtenha derrotando Brock no ginásio de tipo Pedra ou compre aqui!",
		value: 300,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Insignia"],
	},
	{
		id: 12,
		img: "../img/Insignia_Cascata.webp",
		nameItem: "Insígnia Cascata",
		description:
			"Insígnia Cascata, obtenha derrotando Misty no ginásio de tipo Água ou compre aqui!",
		value: 350,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Insignia"],
	},
	{
		id: 13,
		img: "../img/Insignia_Trovao.webp",
		nameItem: "Insígnia Trovao",
		description:
			"Insígnia Trovao, obtenha derrotando Sg. Surge no ginásio de tipo Elétrico ou compre aqui!",
		value: 400,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Insignia"],
	},
	{
		id: 14,
		img: "../img/Insignia_Arco-iris.webp",
		nameItem: "Insígnia Arco-íris",
		description:
			"Insígnia Arco-íris, obtenha derrotando Erika no ginásio de tipo Planta ou compre aqui!",
		value: 600,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Insignia"],
	},
	{
		id: 15,
		img: "../img/Insignia_Alma.webp",
		nameItem: "Insígnia Alma",
		description:
			"Insígnia Alma, obtenha derrotando Koga no ginásio de tipo Veneno ou compre aqui!",
		value: 650,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Insignia"],
	},
	{
		id: 16,
		img: "../img/Insignia_Pantano.webp",
		nameItem: "Insígnia Pântano",
		description:
			"Insígnia Pântano, obtenha derrotando Sabrina no ginásio de tipo Psíquico ou compre aqui!",
		value: 800,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Insignia"],
	},
	{
		id: 17,
		img: "../img/Insignia_Vulcao.webp",
		nameItem: "Insígnia Vulcão",
		description:
			"Insígnia da Vulcão, obtenha derrotando Blaine no ginásio de tipo Fogo ou compre aqui!",
		value: 900,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Insignia"],
	},
	{
		id: 18,
		img: "../img/Insignia_Terra.webp",
		nameItem: "Insígnia Terra",
		description:
			"Insígnia da Terra, obtenha derrotando Giovanni no ginásio de tipo Terra ou compre aqui!",
		value: 1000,
		addCart: "Adicionar ao carrinho",
		qtd: 0,
		tag: ["Insignia"],
	},
];
